apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend
spec:
  serviceName: frontend
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/nice-ocean-373118/client-image:1.5
        ports:
        - containerPort: 3000