apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongovol
          mountPath: /data/db
        envFrom:
        - configMapRef:
           name: mongodb-config-map
      volumes:
      - name: mongovol
        persistentVolumeClaim:
          claimName: mongo-pvc