apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.0.17
          # env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongo-creds
          #       key: username
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongo-creds
          #       key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: pvc
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi